# Generated by Django 4.2.4 on 2023-08-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminModule', '0004_book_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
