# Generated by Django 4.2.4 on 2023-08-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_date_joined_student_last_joined_student_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(),
        ),
    ]
