# Generated by Django 4.2.4 on 2023-08-22 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_student_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='last_joined',
        ),
    ]
